#ifndef DLL_SERIALPORT_GLOBAL_H
#define DLL_SERIALPORT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLL_SERIALPORT_LIBRARY)
#  define DLL_SERIALPORTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DLL_SERIALPORTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLL_SERIALPORT_GLOBAL_H
